### ISSUE TITLE
selecting potential nodes doesn't highlight node

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/nycmesh.net#39]
When selecting active nodes the blue sector range disappears highlighting the node. Selecting potential nodes should do the same.

<img width="345" alt="screen shot 2018-10-27 at 11 38 38 am" src="https://user-images.githubusercontent.com/1037006/47606255-5ca43580-d9df-11e8-83b5-d3ce50558ba8.png">

<img width="381" alt="screen shot 2018-10-27 at 11 37 07 am" src="https://user-images.githubusercontent.com/1037006/47606243-2797e300-d9df-11e8-80b1-756da9533cf4.png">

**Comment by bhny** [comment]
Also related- potential links disappear when highlighting active node. Makes it very confusing to plan things.
<img width="146" alt="screen shot 2018-10-27 at 1 51 48 pm" src="https://user-images.githubusercontent.com/1037006/47607549-7c435a00-d9ef-11e8-9ad1-64afdcd9a929.png">
<img width="169" alt="screen shot 2018-10-27 at 1 51 38 pm" src="https://user-images.githubusercontent.com/1037006/47607550-7c435a00-d9ef-11e8-89f5-bd1f45965c75.png">

**Comment by olivernyc** [comment]
Should be fixed by https://github.com/nycmeshnet/node-map/commit/ddb1ee3f2b90f315f6463dd0b297ed6bc637a66d

<img width="500" alt="screen shot 2018-10-27 at 5 45 28 pm" src="https://user-images.githubusercontent.com/28816316/47609598-1ddaa380-da10-11e8-84fe-9394142e6aed.png">
<img width="400" alt="screen shot 2018-10-27 at 5 43 04 pm" src="https://user-images.githubusercontent.com/28816316/47609594-ef5cc880-da0f-11e8-95ac-d4d3e8c47486.png">

**Comment by bhny** [comment]
still getting this problem with potential links-

<img width="407" alt="no-potential" src="https://user-images.githubusercontent.com/1037006/47893596-0f3b2480-de34-11e8-8ca0-1fd9eb6d4aac.png">

<img width="407" alt="no-potential" src="https://user-images.githubusercontent.com/1037006/47893599-14986f00-de34-11e8-9139-0a66b02611e6.png">

**Comment by olivernyc** [comment]
Fixed in https://github.com/nycmeshnet/node-map/commit/a46dbd1911d1fa02f3e22c31cf084dc5dac907b8
